import { Trip, Expense, Hotel } from '../types';

export const useMockData = (): { trips: Trip[], expenses: Expense[] } => {
  const trips: Trip[] = [
    {
      id: '1',
      destination: 'Kyoto, Japan',
      startDate: 'Oct 12, 2024',
      endDate: 'Oct 20, 2024',
      imageUrl: 'https://picsum.photos/seed/kyoto/400/300',
      status: 'Upcoming',
      budget: 2500,
      description: 'Immerse yourself in the cultural heart of Japan. Explore ancient temples, serene gardens, and traditional geisha districts in the former imperial capital.',
      places: [
        { name: 'Kinkaku-ji (Golden Pavilion)', description: 'A stunning Zen Buddhist temple covered in gold leaf, reflecting beautifully in its large pond.', imageUrl: 'https://picsum.photos/seed/kinkakuji/400/300' },
        { name: 'Fushimi Inari Shrine', description: 'Famous for its thousands of vibrant red torii gates that wind through a wooded forest.', imageUrl: 'https://picsum.photos/seed/fushimiinari/400/300' },
        { name: 'Arashiyama Bamboo Grove', description: 'Walk through a magical, otherworldly path lined with towering bamboo stalks.', imageUrl: 'https://picsum.photos/seed/arashiyama/400/300' },
      ],
      suggestedHotels: [
        { name: 'Hyatt Regency Kyoto', pricePerNight: 350, imageUrls: ['https://picsum.photos/seed/hyattkyoto1/400/300', 'https://picsum.photos/seed/hyattkyoto2/400/300', 'https://picsum.photos/seed/hyattkyoto3/400/300'], rating: 4.5, address: '644-2 Sanjusangendomawari, Higashiyama Ward' },
        { name: 'The Ritz-Carlton, Kyoto', pricePerNight: 800, imageUrls: ['https://picsum.photos/seed/ritzkyoto1/400/300', 'https://picsum.photos/seed/ritzkyoto2/400/300'], rating: 5.0, address: 'Kamogawa Nijo-Ohashi Hotori, Nakagyo Ward' },
        { name: 'Hotel Kanra Kyoto', pricePerNight: 280, imageUrls: ['https://picsum.photos/seed/kanrakyoto1/400/300', 'https://picsum.photos/seed/kanrakyoto2/400/300', 'https://picsum.photos/seed/kanrakyoto3/400/300'], rating: 4.7, address: '190 Kitamachi, Shimogyo Ward' },
      ],
      suggestedFlights: [
        { airline: 'Japan Airlines', flightNumber: 'JL007', departureTime: '08:00 AM', arrivalTime: '10:30 PM', price: 1200, airlineLogoUrl: 'https://picsum.photos/seed/jal/100/100' },
        { airline: 'All Nippon Airways', flightNumber: 'NH205', departureTime: '09:30 AM', arrivalTime: '11:45 PM', price: 1150, airlineLogoUrl: 'https://picsum.photos/seed/ana/100/100' },
      ],
    },
    {
      id: '2',
      destination: 'Rome, Italy',
      startDate: 'Aug 15, 2024',
      endDate: 'Aug 22, 2024',
      imageUrl: 'https://picsum.photos/seed/rome/400/300',
      status: 'Upcoming',
      budget: 3000,
      description: 'Discover the "Eternal City", a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture and culture on display.',
      places: [
          { name: 'Colosseum', description: 'An iconic oval amphitheatre in the centre of the city, the largest ancient amphitheatre ever built.', imageUrl: 'https://picsum.photos/seed/colosseum/400/300' },
          { name: 'Vatican City', description: 'Home to the Pope, St. Peter\'s Basilica, and the Vatican Museums, which house ancient Roman sculptures.', imageUrl: 'https://picsum.photos/seed/vatican/400/300' },
          { name: 'Trevi Fountain', description: 'The largest Baroque fountain in the city and one of the most famous fountains in the world.', imageUrl: 'https://picsum.photos/seed/trevi/400/300' },
      ],
      suggestedHotels: [
        { name: 'Hotel Artemide', pricePerNight: 250, imageUrls: ['https://picsum.photos/seed/artemide1/400/300', 'https://picsum.photos/seed/artemide2/400/300'], rating: 4.8, address: 'Via Nazionale, 22, 00184 Roma RM' },
        { name: 'The St. Regis Rome', pricePerNight: 700, imageUrls: ['https://picsum.photos/seed/stregisrome1/400/300', 'https://picsum.photos/seed/stregisrome2/400/300', 'https://picsum.photos/seed/stregisrome3/400/300'], rating: 4.9, address: 'Via Vittorio Emanuele Orlando, 3' },
        { name: 'iQ Hotel Roma', pricePerNight: 180, imageUrls: ['https://picsum.photos/seed/iqroma1/400/300', 'https://picsum.photos/seed/iqroma2/400/300'], rating: 4.4, address: 'Via Firenze, 8, 00184 Roma RM' },
      ],
       suggestedFlights: [
        { airline: 'ITA Airways', flightNumber: 'AZ609', departureTime: '10:00 AM', arrivalTime: '12:30 PM', price: 450, airlineLogoUrl: 'https://picsum.photos/seed/ita/100/100' },
        { airline: 'Ryanair', flightNumber: 'FR9634', departureTime: '07:15 AM', arrivalTime: '09:40 AM', price: 280, airlineLogoUrl: 'https://picsum.photos/seed/ryanair/100/100' },
      ],
    },
    {
      id: '3',
      destination: 'Santorini, Greece',
      startDate: 'Jul 05, 2024',
      endDate: 'Jul 12, 2024',
      imageUrl: 'https://picsum.photos/seed/santorini/400/300',
      status: 'Current',
      budget: 4000,
      description: 'Experience one of the most iconic Greek islands, known for its dramatic views, stunning sunsets from Oia town, and its very own active volcano.',
      places: [
          { name: 'Oia Village', description: 'Famous for its stunning sunsets, whitewashed houses, and blue-domed churches.', imageUrl: 'https://picsum.photos/seed/oia/400/300' },
          { name: 'Red Beach', description: 'A unique beach with red-hued volcanic sand and towering red cliffs.', imageUrl: 'https://picsum.photos/seed/redbeach/400/300' },
          { name: 'Akrotiri Archaeological Site', description: 'A prehistoric Minoan city preserved in volcanic ash, often called the "Minoan Pompeii".', imageUrl: 'https://picsum.photos/seed/akrotiri/400/300' },
      ],
      suggestedHotels: [
        { name: 'Canaves Oia Suites', pricePerNight: 950, imageUrls: ['https://picsum.photos/seed/canaves1/400/300', 'https://picsum.photos/seed/canaves2/400/300', 'https://picsum.photos/seed/canaves3/400/300'], rating: 5.0, address: 'Main Street, Oia 84702' },
        { name: 'Grace Hotel, Auberge Resorts', pricePerNight: 1200, imageUrls: ['https://picsum.photos/seed/gracehotel1/400/300', 'https://picsum.photos/seed/gracehotel2/400/300'], rating: 5.0, address: 'Imerovigli, 84700' },
        { name: 'Astra Suites', pricePerNight: 600, imageUrls: ['https://picsum.photos/seed/astra1/400/300', 'https://picsum.photos/seed/astra2/400/300', 'https://picsum.photos/seed/astra3/400/300'], rating: 4.8, address: 'Imerovigli, 84700' },
      ],
    },
     {
      id: '4',
      destination: 'Paris, France',
      startDate: 'May 20, 2024',
      endDate: 'May 27, 2024',
      imageUrl: 'https://picsum.photos/seed/paris/400/300',
      status: 'Past',
      budget: 3500,
      description: 'The "City of Light" is a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine.',
      places: [
          { name: 'Eiffel Tower', description: 'An iconic wrought-iron lattice tower on the Champ de Mars, a global cultural icon of France.', imageUrl: 'https://picsum.photos/seed/eiffel/400/300' },
          { name: 'Louvre Museum', description: 'The world\'s largest art museum and a historic monument, home to masterpieces like the Mona Lisa.', imageUrl: 'https://picsum.photos/seed/louvre/400/300' },
          { name: 'Notre-Dame Cathedral', description: 'A medieval Catholic cathedral, widely considered to be one of the finest examples of French Gothic architecture.', imageUrl: 'https://picsum.photos/seed/notredame/400/300' },
      ],
      suggestedHotels: [
        { name: 'Le Bristol Paris', pricePerNight: 1100, imageUrls: ['https://picsum.photos/seed/bristolparis1/400/300', 'https://picsum.photos/seed/bristolparis2/400/300'], rating: 5.0, address: '112 Rue du Faubourg Saint-Honoré' },
        { name: 'Hotel Malte - Astotel', pricePerNight: 220, imageUrls: ['https://picsum.photos/seed/malteparis1/400/300', 'https://picsum.photos/seed/malteparis2/400/300', 'https://picsum.photos/seed/malteparis3/400/300'], rating: 4.6, address: '63 Rue de Richelieu, 75002 Paris' },
        { name: 'Four Seasons George V', pricePerNight: 1400, imageUrls: ['https://picsum.photos/seed/fourseasonsparis1/400/300', 'https://picsum.photos/seed/fourseasonsparis2/400/300'], rating: 5.0, address: '31 Avenue George V, 75008 Paris' },
      ],
    },
    {
      id: '5',
      destination: 'New York, USA',
      startDate: 'Apr 01, 2024',
      endDate: 'Apr 07, 2024',
      imageUrl: 'https://picsum.photos/seed/newyork/400/300',
      status: 'Past',
      budget: 2000,
      description: 'The "Big Apple" is a city of superlatives: an iconic global center of culture, finance, media, and entertainment.',
      places: [
        { name: 'Statue of Liberty', description: 'A colossal neoclassical sculpture on Liberty Island in New York Harbor.', imageUrl: 'https://picsum.photos/seed/liberty/400/300' },
        { name: 'Central Park', description: 'An urban park in Manhattan, it is the most visited urban park in the United States.', imageUrl: 'https://picsum.photos/seed/centralpark/400/300' },
        { name: 'Times Square', description: 'A major commercial intersection, tourist destination, and entertainment center.', imageUrl: 'https://picsum.photos/seed/timessquare/400/300' },
      ],
      suggestedHotels: [
        { name: 'The Peninsula New York', pricePerNight: 850, imageUrls: ['https://picsum.photos/seed/peninsulanyc1/400/300', 'https://picsum.photos/seed/peninsulanyc2/400/300'], rating: 4.7, address: '700 5th Ave, New York, NY 10019' },
        { name: 'CitizenM Bowery', pricePerNight: 250, imageUrls: ['https://picsum.photos/seed/citizenmnyc1/400/300', 'https://picsum.photos/seed/citizenmnyc2/400/300', 'https://picsum.photos/seed/citizenmnyc3/400/300'], rating: 4.5, address: '189 Bowery, New York, NY 10002' },
        { name: 'The Plaza', pricePerNight: 900, imageUrls: ['https://picsum.photos/seed/plazanyc1/400/300', 'https://picsum.photos/seed/plazanyc2/400/300'], rating: 4.6, address: 'Fifth Avenue at Central Park South, New York' },
      ],
    },
    {
      id: '6',
      destination: 'Cairo, Egypt',
      startDate: 'Nov 05, 2024',
      endDate: 'Nov 12, 2024',
      imageUrl: 'https://picsum.photos/seed/cairo/400/300',
      status: 'Upcoming',
      budget: 2800,
      description: 'Explore the capital of Egypt, a vast metropolis set on the Nile River. At its heart are Tahrir Square and the vast Egyptian Museum, a trove of antiquities.',
      places: [
        { name: 'Pyramids of Giza', description: 'The sole surviving wonder of the ancient world, including the Great Pyramid, Khafre, and Menkaure.', imageUrl: 'https://picsum.photos/seed/giza/400/300' },
        { name: 'Khan el-Khalili', description: 'A famous bazaar and souq in the historic center of Cairo, Egypt.', imageUrl: 'https://picsum.photos/seed/khan/400/300' },
        { name: 'The Egyptian Museum', description: 'Home to an extensive collection of ancient Egyptian antiquities, including the treasures of Tutankhamun.', imageUrl: 'https://picsum.photos/seed/museumcairo/400/300' },
      ],
      suggestedHotels: [
        { name: 'Four Seasons Hotel Cairo at Nile Plaza', pricePerNight: 400, imageUrls: ['https://picsum.photos/seed/fscairo1/400/300', 'https://picsum.photos/seed/fscairo2/400/300'], rating: 4.8, address: '1089 Corniche El Nil, Garden City' },
        { name: 'Kempinski Nile Hotel', pricePerNight: 280, imageUrls: ['https://picsum.photos/seed/kempinskicairo1/400/300', 'https://picsum.photos/seed/kempinskicairo2/400/300'], rating: 4.7, address: '12 Ahmed Ragheb Street, Garden City' },
        { name: 'Steigenberger El Tahrir Cairo', pricePerNight: 150, imageUrls: ['https://picsum.photos/seed/steigenbergercairo1/400/300', 'https://picsum.photos/seed/steigenbergercairo2/400/300'], rating: 4.4, address: '2, Kasr Al Nile street, Tahrir Square' },
      ],
    },
    {
      id: '7',
      destination: 'Queenstown, New Zealand',
      startDate: 'Feb 10, 2025',
      endDate: 'Feb 18, 2025',
      imageUrl: 'https://picsum.photos/seed/queenstown/400/300',
      status: 'Upcoming',
      budget: 4500,
      description: 'Known as the adventure capital of the world, Queenstown is nestled on the shores of Lake Wakatipu and surrounded by the majestic Southern Alps. It\'s a paradise for thrill-seekers and nature lovers alike.',
      places: [
        { name: 'Milford Sound', description: 'A breathtaking fiord known for its towering Mitre Peak, rainforests, and waterfalls.', imageUrl: 'https://picsum.photos/seed/milford/400/300' },
        { name: 'Skyline Queenstown', description: 'Ride the gondola for panoramic views, luge rides, and mountaintop dining.', imageUrl: 'https://picsum.photos/seed/skyline/400/300' },
        { name: 'Bungy Jumping (Kawarau Bridge)', description: 'Experience the original bungy jump at the Kawarau Gorge Suspension Bridge.', imageUrl: 'https://picsum.photos/seed/bungy/400/300' },
      ],
      suggestedHotels: [
        { name: 'Eichardt\'s Private Hotel', pricePerNight: 1300, imageUrls: ['https://picsum.photos/seed/eichardts1/400/300', 'https://picsum.photos/seed/eichardts2/400/300'], rating: 5.0, address: 'Marine Parade, Queenstown 9300' },
        { name: 'The Rees Hotel & Luxury Apartments', pricePerNight: 450, imageUrls: ['https://picsum.photos/seed/therees1/400/300', 'https://picsum.photos/seed/therees2/400/300'], rating: 4.8, address: '377 Frankton Road, Queenstown 9300' },
        { name: 'QT Queenstown', pricePerNight: 350, imageUrls: ['https://picsum.photos/seed/qtqueenstown1/400/300', 'https://picsum.photos/seed/qtqueenstown2/400/300', 'https://picsum.photos/seed/qtqueenstown3/400/300'], rating: 4.6, address: '30 Brunswick Street, Queenstown 9300' },
      ],
    },
    {
      id: '8',
      destination: 'Machu Picchu, Peru',
      startDate: 'Jun 05, 2025',
      endDate: 'Jun 12, 2025',
      imageUrl: 'https://picsum.photos/seed/machupicchu/400/300',
      status: 'Upcoming',
      budget: 3200,
      description: 'Discover the mystical Incan citadel set high in the Andes Mountains. This UNESCO World Heritage site is renowned for its sophisticated dry-stone walls that fuse huge blocks without the use of mortar.',
      places: [
        { name: 'Sun Gate (Inti Punku)', description: 'The original entrance to Machu Picchu, offering a classic, breathtaking first view of the citadel.', imageUrl: 'https://picsum.photos/seed/sungate/400/300' },
        { name: 'Huayna Picchu', description: 'The iconic mountain behind Machu Picchu. A challenging hike rewards you with incredible views from the top.', imageUrl: 'https://picsum.photos/seed/huaynapicchu/400/300' },
        { name: 'Temple of the Sun', description: 'A unique semi-circular construction built over a massive rock, used for astronomical observations.', imageUrl: 'https://picsum.photos/seed/templesun/400/300' },
      ],
      suggestedHotels: [
        { name: 'Belmond Sanctuary Lodge', pricePerNight: 1500, imageUrls: ['https://picsum.photos/seed/sanctuarylodge1/400/300', 'https://picsum.photos/seed/sanctuarylodge2/400/300'], rating: 4.9, address: 'Carretera Hiram Bingham KM 7.5' },
        { name: 'Inkaterra Machu Picchu Pueblo Hotel', pricePerNight: 600, imageUrls: ['https://picsum.photos/seed/inkaterraperu1/400/300', 'https://picsum.photos/seed/inkaterraperu2/400/300'], rating: 4.8, address: 'Aguas Calientes 08681, Peru' },
        { name: 'Sumaq Machu Picchu Hotel', pricePerNight: 550, imageUrls: ['https://picsum.photos/seed/sumaqperu1/400/300', 'https://picsum.photos/seed/sumaqperu2/400/300', 'https://picsum.photos/seed/sumaqperu3/400/300'], rating: 4.7, address: 'Avenida Hermanos Ayar Mz 1 Lote 3' },
      ],
    },
    {
      id: '9',
      destination: 'Reykjavik, Iceland',
      startDate: 'Mar 01, 2025',
      endDate: 'Mar 08, 2025',
      imageUrl: 'https://picsum.photos/seed/reykjavik/400/300',
      status: 'Upcoming',
      budget: 3800,
      description: 'Journey to the land of fire and ice. Discover stunning glaciers, powerful geysers, the magical Northern Lights, and the unique culture of Iceland\'s capital.',
      places: [
        { name: 'Blue Lagoon', description: 'A world-famous geothermal spa known for its milky-blue, mineral-rich waters.', imageUrl: 'https://picsum.photos/seed/bluelagoon/400/300' },
        { name: 'Golden Circle', description: 'A classic tourist route covering Þingvellir National Park, Gullfoss Waterfall, and the Geysir Geothermal Area.', imageUrl: 'https://picsum.photos/seed/goldencircle/400/300' },
        { name: 'Hallgrímskirkja', description: 'A towering, modern Lutheran church with a distinctive design inspired by basalt columns.', imageUrl: 'https://picsum.photos/seed/hallgrimskirkja/400/300' },
      ],
      suggestedHotels: [
        { name: 'The Reykjavik EDITION', pricePerNight: 650, imageUrls: ['https://picsum.photos/seed/editionreykjavik1/400/300', 'https://picsum.photos/seed/editionreykjavik2/400/300'], rating: 4.9, address: 'Austurbakki 2, 101 Reykjavik' },
        { name: 'Sand Hotel by Keahotels', pricePerNight: 320, imageUrls: ['https://picsum.photos/seed/sandhotel1/400/300', 'https://picsum.photos/seed/sandhotel2/400/300'], rating: 4.7, address: 'Laugavegur 34, 101 Reykjavik' },
        { name: 'Canopy by Hilton Reykjavik', pricePerNight: 400, imageUrls: ['https://picsum.photos/seed/canopyreykjavik1/400/300', 'https://picsum.photos/seed/canopyreykjavik2/400/300'], rating: 4.6, address: 'Smidjustigur 4, 101 Reykjavik' },
      ],
    },
    {
      id: '10',
      destination: 'Bangkok, Thailand',
      startDate: 'Apr 10, 2025',
      endDate: 'Apr 18, 2025',
      imageUrl: 'https://picsum.photos/seed/bangkok/400/300',
      status: 'Upcoming',
      budget: 2200,
      description: 'Dive into the vibrant chaos of Bangkok. From ornate shrines and bustling street markets to modern megamalls and a legendary nightlife, the city is a sensory overload.',
      places: [
        { name: 'The Grand Palace', description: 'A complex of stunning buildings that has been the official residence of the Kings of Siam since 1782.', imageUrl: 'https://picsum.photos/seed/grandpalace/400/300' },
        { name: 'Wat Arun (Temple of Dawn)', description: 'A striking riverside temple famous for its intricate design made of colourful glass and Chinese porcelain.', imageUrl: 'https://picsum.photos/seed/watarun/400/300' },
        { name: 'Chatuchak Weekend Market', description: 'One of the world\'s largest outdoor markets, with over 15,000 stalls selling everything imaginable.', imageUrl: 'https://picsum.photos/seed/chatuchak/400/300' },
      ],
      suggestedHotels: [
        { name: 'Mandarin Oriental, Bangkok', pricePerNight: 700, imageUrls: ['https://picsum.photos/seed/mandarinbkk1/400/300', 'https://picsum.photos/seed/mandarinbkk2/400/300'], rating: 4.9, address: '48 Oriental Avenue, Bangkok 10500' },
        { name: 'SO/ Bangkok', pricePerNight: 250, imageUrls: ['https://picsum.photos/seed/sobkk1/400/300', 'https://picsum.photos/seed/sobkk2/400/300', 'https://picsum.photos/seed/sobkk3/400/300'], rating: 4.7, address: '2 North Sathorn Road, Bangrak' },
        { name: 'Avani+ Riverside Bangkok Hotel', pricePerNight: 180, imageUrls: ['https://picsum.photos/seed/avanibkk1/400/300', 'https://picsum.photos/seed/avanibkk2/400/300'], rating: 4.6, address: '257 Charoennakorn Road, Thonburi' },
      ],
    },
    {
      id: '11',
      destination: 'Rio de Janeiro, Brazil',
      startDate: 'Jan 15, 2025',
      endDate: 'Jan 22, 2025',
      imageUrl: 'https://picsum.photos/seed/rio/400/300',
      status: 'Upcoming',
      budget: 3100,
      description: 'Experience the vibrant culture of Rio, from the world-famous Copacabana and Ipanema beaches to the iconic Christ the Redeemer statue atop Mount Corcovado.',
      places: [
        { name: 'Christ the Redeemer', description: 'An Art Deco statue of Jesus Christ, located at the peak of Corcovado mountain.', imageUrl: 'https://picsum.photos/seed/christredeemer/400/300' },
        { name: 'Sugarloaf Mountain', description: 'A peak situated at the mouth of Guanabara Bay, offering panoramic views of the city.', imageUrl: 'https://picsum.photos/seed/sugarloaf/400/300' },
        { name: 'Copacabana Beach', description: 'One of the most famous beaches in the world, known for its lively atmosphere.', imageUrl: 'https://picsum.photos/seed/copacabana/400/300' },
      ],
      suggestedHotels: [
        { name: 'Belmond Copacabana Palace', pricePerNight: 600, imageUrls: ['https://picsum.photos/seed/copapalace1/400/300', 'https://picsum.photos/seed/copapalace2/400/300'], rating: 4.8, address: 'Avenida Atlântica 1702, Copacabana' },
        { name: 'Hotel Fasano Rio de Janeiro', pricePerNight: 750, imageUrls: ['https://picsum.photos/seed/fasanorio1/400/300', 'https://picsum.photos/seed/fasanorio2/400/300'], rating: 4.7, address: 'Av. Vieira Souto, 80 - Ipanema' },
      ],
    },
    {
      id: '12',
      destination: 'Marrakech, Morocco',
      startDate: 'May 05, 2025',
      endDate: 'May 12, 2025',
      imageUrl: 'https://picsum.photos/seed/marrakech/400/300',
      status: 'Upcoming',
      budget: 1900,
      description: 'Get lost in the bustling souks, serene riads, and vibrant Djemaa el-Fna square of this magical Moroccan city.',
      places: [
        { name: 'Jardin Majorelle', description: 'A stunning botanical garden and artist\'s landscape garden, once owned by Yves Saint Laurent.', imageUrl: 'https://picsum.photos/seed/majorelle/400/300' },
        { name: 'Bahia Palace', description: 'A 19th-century palace showcasing intricate Moroccan architecture and craftsmanship.', imageUrl: 'https://picsum.photos/seed/bahia/400/300' },
        { name: 'Djemaa el-Fna', description: 'The main square of Marrakech, filled with snake charmers, storytellers, and food stalls.', imageUrl: 'https://picsum.photos/seed/djemaa/400/300' },
      ],
      suggestedHotels: [
        { name: 'La Mamounia', pricePerNight: 800, imageUrls: ['https://picsum.photos/seed/mamounia1/400/300', 'https://picsum.photos/seed/mamounia2/400/300'], rating: 4.9, address: 'Avenue Bab Jdid, Marrakesh' },
        { name: 'Riad Kniza', pricePerNight: 450, imageUrls: ['https://picsum.photos/seed/kniza1/400/300', 'https://picsum.photos/seed/kniza2/400/300'], rating: 5.0, address: '34 Derb l\'Hotel, Bab Doukkala' },
      ],
    },
    {
      id: '13',
      destination: 'Seoul, South Korea',
      startDate: 'Sep 20, 2024',
      endDate: 'Sep 28, 2024',
      imageUrl: 'https://picsum.photos/seed/seoul/400/300',
      status: 'Upcoming',
      budget: 2700,
      description: 'Discover a city where modern skyscrapers and high-tech subways meet Buddhist temples, palaces, and street markets.',
      places: [
        { name: 'Gyeongbok Palace', description: 'The largest of the Five Grand Palaces built during the Joseon Dynasty.', imageUrl: 'https://picsum.photos/seed/gyeongbok/400/300' },
        { name: 'Myeongdong Market', description: 'A bustling shopping district with a vast array of Korean cosmetics, fashion, and street food.', imageUrl: 'https://picsum.photos/seed/myeongdong/400/300' },
        { name: 'N Seoul Tower', description: 'Offers panoramic views of the city from its observation deck, a popular spot for couples.', imageUrl: 'https://picsum.photos/seed/nseoultower/400/300' },
      ],
      suggestedHotels: [
        { name: 'Signiel Seoul', pricePerNight: 500, imageUrls: ['https://picsum.photos/seed/signielseoul1/400/300', 'https://picsum.photos/seed/signielseoul2/400/300'], rating: 4.8, address: '300 Olympic-ro, Songpa-gu, Seoul' },
        { name: 'Lotte Hotel Seoul', pricePerNight: 350, imageUrls: ['https://picsum.photos/seed/lotteseoul1/400/300', 'https://picsum.photos/seed/lotteseoul2/400/300'], rating: 4.6, address: '30 Eulji-ro, Jung-gu, Seoul' },
      ],
    },
    {
      id: '14',
      destination: 'Vancouver, Canada',
      startDate: 'Jul 20, 2024',
      endDate: 'Jul 27, 2024',
      imageUrl: 'https://picsum.photos/seed/vancouver/400/300',
      status: 'Current',
      budget: 3300,
      description: 'Explore the stunning natural beauty of Vancouver, a city nestled between the mountains and the ocean, offering outdoor adventures and a vibrant urban core.',
      places: [
        { name: 'Stanley Park', description: 'A magnificent, sprawling urban park with scenic seawall, beaches, and hiking trails.', imageUrl: 'https://picsum.photos/seed/stanleypark/400/300' },
        { name: 'Granville Island', description: 'A bustling arts and crafts community with a famous public market, galleries, and theaters.', imageUrl: 'https://picsum.photos/seed/granville/400/300' },
        { name: 'Capilano Suspension Bridge', description: 'A thrilling suspension bridge that hangs 70 meters above the Capilano River.', imageUrl: 'https://picsum.photos/seed/capilano/400/300' },
      ],
      suggestedHotels: [
        { name: 'Fairmont Pacific Rim', pricePerNight: 650, imageUrls: ['https://picsum.photos/seed/fairmontvan1/400/300', 'https://picsum.photos/seed/fairmontvan2/400/300'], rating: 4.9, address: '1038 Canada Pl, Vancouver, BC' },
        { name: 'Rosewood Hotel Georgia', pricePerNight: 580, imageUrls: ['https://picsum.photos/seed/rosewoodvan1/400/300', 'https://picsum.photos/seed/rosewoodvan2/400/300'], rating: 4.8, address: '801 W Georgia St, Vancouver, BC' },
      ],
    },
    {
      id: '15',
      destination: 'Dubai, UAE',
      startDate: 'Dec 10, 2024',
      endDate: 'Dec 17, 2024',
      imageUrl: 'https://picsum.photos/seed/dubai/400/300',
      status: 'Upcoming',
      budget: 5000,
      description: 'Experience the futuristic city of Dubai, known for its luxury shopping, ultramodern architecture, and a lively nightlife scene.',
      places: [
        { name: 'Burj Khalifa', description: 'The tallest building in the world, offering breathtaking views from its observation decks.', imageUrl: 'https://picsum.photos/seed/burjkhalifa/400/300' },
        { name: 'The Dubai Mall', description: 'A massive shopping mall with an aquarium, an ice rink, and countless retail stores.', imageUrl: 'https://picsum.photos/seed/dubaimall/400/300' },
        { name: 'Desert Safari', description: 'An adventurous trip into the Arabian desert with dune bashing, camel riding, and traditional entertainment.', imageUrl: 'https://picsum.photos/seed/desertsafari/400/300' },
      ],
      suggestedHotels: [
        { name: 'Burj Al Arab Jumeirah', pricePerNight: 1500, imageUrls: ['https://picsum.photos/seed/burjalarab1/400/300', 'https://picsum.photos/seed/burjalarab2/400/300'], rating: 5.0, address: 'Umm Suqeim 3, Dubai' },
        { name: 'Atlantis, The Palm', pricePerNight: 700, imageUrls: ['https://picsum.photos/seed/atlantisdubai1/400/300', 'https://picsum.photos/seed/atlantisdubai2/400/300'], rating: 4.7, address: 'Crescent Rd, The Palm Jumeirah' },
      ],
    },
  ];

  const expenses: Expense[] = [
    { id: 'e1', tripId: '3', category: 'Food', description: 'Dinner at seaside restaurant', amount: 85, date: 'Jul 05, 2024' },
    { id: 'e2', tripId: '3', category: 'Transport', description: 'ATV rental for the day', amount: 120, date: 'Jul 06, 2024' },
    { id: 'e3', tripId: '3', category: 'Activities', description: 'Boat tour to volcano', amount: 150, date: 'Jul 07, 2024' },
    { id: 'e4', tripId: '4', category: 'Accommodation', description: 'Hotel payment final installment', amount: 800, date: 'May 20, 2024' },
    { id: 'e5', tripId: '4', category: 'Food', description: 'Croissants and coffee', amount: 15, date: 'May 21, 2024' },
    { id: 'e6', tripId: '14', category: 'Food', description: 'Lunch at Granville Market', amount: 55, date: 'Jul 20, 2024' },
    { id: 'e7', tripId: '14', category: 'Activities', description: 'Tickets to Capilano Bridge', amount: 120, date: 'Jul 21, 2024' },
  ];

  return { trips, expenses };
};